INSERT
    INTO
        orders(
            id,
            buyer_id,
            status,
            price
        )
    VALUES(
        'order-id-1',
        'buyer-id-1',
        'CREATED',
        100.00
    );