[versions]
spring-boot = "3.4.2"
spring-cloud = "2024.0.0"

[libraries]
springBootDependencies = { module = "org.springframework.boot:spring-boot-dependencies", version.ref = "spring-boot" }
springCloudDependencies = { module = "org.springframework.cloud:spring-cloud-dependencies", version.ref = "spring-cloud" }

[bundles]

[plugins]
springBoot = { id = "org.springframework.boot", version.ref = "spring-boot" }