[versions]
dependency-management-plugin = "1.1.6"
spring-boot = "3.3.4"
spring-cloud = "2023.0.3"
spring-cloud-contract = "4.1.4"

[libraries]
dependencyManagementPlugin = { module = "io.spring.gradle:dependency-management-plugin", version.ref = "dependency-management-plugin" }
springBootDependencies = { module = "org.springframework.boot:spring-boot-dependencies", version.ref = "spring-boot" }
springCloudDependencies = { module = "org.springframework.cloud:spring-cloud-dependencies", version.ref = "spring-cloud" }

[bundles]

[plugins]
springCloudContract = { id = "org.springframework.cloud.contract", version.ref = "spring-cloud-contract" }
springBoot = { id = "org.springframework.boot", version.ref = "spring-boot" }